import type { CSSProperties, ReactNode } from "react";
import { DocumentWave } from "@/components/billing/shared/DocumentWave";
import { money } from "@/lib/format";
import type { AppSettings, Invoice, TemplateConfig } from "@/types/db";

const defaults:TemplateConfig={paperSize:"A4",orientation:"portrait",primaryColor:"#111827",backgroundStyle:"clean",fontFamily:"Arial",logoWidth:180,stampWidth:150,sections:["header","billTo","billingDetails","items","totals","paymentInstructions","terms","stamp"],visibility:{companyPhone:true,companyEmail:true,companyWebsite:true,clientAddress:true,clientEmail:true,clientPhone:true,contractReference:true,purchaseOrderReference:true,discount:true,previousBalance:true},labels:{invoiceTitle:"INVOICE",billTo:"BILL TO",services:"SERVICES PROVIDED",totalDue:"TOTAL DUE"}};
function configOf(invoice:Invoice){const source=(invoice.finalized_at?invoice.template_snapshot:invoice.template?.config) as Partial<TemplateConfig>|undefined;return {...defaults,...source,visibility:{...defaults.visibility,...source?.visibility},labels:{...defaults.labels,...source?.labels}}}

export function InvoiceDocument({invoice,liveSettings,logoUrl,stampUrl}:{invoice:Invoice;liveSettings?:AppSettings|null;logoUrl?:string|null;stampUrl?:string|null}){
  const config=configOf(invoice),saved=invoice.company_snapshot as Record<string,any>,clientSaved=invoice.client_snapshot as Record<string,any>;
  const company=invoice.finalized_at?saved:{name:liveSettings?.company_name,tagline:liveSettings?.company_tagline,phone:liveSettings?.company_phone,email:liveSettings?.company_email,website:liveSettings?.company_website,footer:liveSettings?.default_footer,cashEnabled:liveSettings?.cash_enabled,omtEnabled:liveSettings?.omt_enabled,omtRecipientName:liveSettings?.omt_recipient_name,omtPhone:liveSettings?.omt_phone,whishEnabled:liveSettings?.whish_enabled,whishRecipientName:liveSettings?.whish_recipient_name,whishPhone:liveSettings?.whish_phone};
  const client=invoice.finalized_at?clientSaved:{billingName:invoice.contact?.billing_name||invoice.contact?.name,contactName:invoice.contact?.billing_contact,address:invoice.contact?.billing_address,email:invoice.contact?.email,phone:invoice.contact?.whatsapp};
  const str=(value:unknown)=>typeof value==="string"?value:"";
  const methods=[company.cashEnabled&&"Cash",company.omtEnabled&&`OMT${company.omtRecipientName?` · ${str(company.omtRecipientName)}`:""}${company.omtPhone?` / ${str(company.omtPhone)}`:""}`,company.whishEnabled&&`Whish${company.whishRecipientName?` · ${str(company.whishRecipientName)}`:""}${company.whishPhone?` / ${str(company.whishPhone)}`:""}`].filter(Boolean);
  const blocks:Record<string,ReactNode>={
    header:<header className="invoice-doc-header" key="header"><div className="invoice-company-brand">{logoUrl?<img className="invoice-logo" src={logoUrl} alt={`${str(company.name)||"Company"} logo`} style={{width:config.logoWidth}}/>:<span className="invoice-logo-fallback">{str(company.name).slice(0,2).toUpperCase()}</span>}<div><p className="invoice-tagline">{str(company.tagline)}</p><h2>{str(company.name)}</h2><div className="invoice-company-lines">{config.visibility.companyPhone&&company.phone&&<span>{str(company.phone)}</span>}{config.visibility.companyEmail&&company.email&&<span>{str(company.email)}</span>}{config.visibility.companyWebsite&&company.website&&<span>{str(company.website)}</span>}</div></div></div><div className="invoice-identity"><small>Billing document</small><p>{config.labels.invoiceTitle}</p><strong>{invoice.invoice_number}</strong><span className={`invoice-doc-status invoice-doc-status-${invoice.status}`}>{invoice.status.replace("_"," ")}</span></div></header>,
    billTo:<section className="invoice-bill-to" key="billTo"><div className="invoice-section-marker">01</div><div><p className="invoice-label">{config.labels.billTo}</p><h3>{str(client.billingName)}</h3>{client.contactName&&<p>{str(client.contactName)}</p>}<div className="client-contact-lines">{config.visibility.clientAddress&&client.address&&<span>{str(client.address)}</span>}{config.visibility.clientEmail&&client.email&&<span>{str(client.email)}</span>}{config.visibility.clientPhone&&client.phone&&<span>{str(client.phone)}</span>}</div></div></section>,
    billingDetails:<section className="invoice-meta" key="billingDetails"><div><span>Invoice date</span><strong>{invoice.invoice_date}</strong></div><div><span>Due date</span><strong>{invoice.due_date}</strong></div><div><span>Currency</span><strong>{invoice.currency}</strong></div>{invoice.service_period_start&&<div><span>Service period</span><strong>{invoice.service_period_start}<br/>{invoice.service_period_end}</strong></div>}{config.visibility.contractReference&&invoice.contract_reference&&<div><span>Contract</span><strong>{invoice.contract_reference}</strong></div>}{config.visibility.purchaseOrderReference&&invoice.purchase_order_reference&&<div><span>PO reference</span><strong>{invoice.purchase_order_reference}</strong></div>}</section>,
    items:<section className="invoice-items" key="items"><div className="invoice-section-title"><span className="invoice-section-marker">02</span><p className="invoice-label">{config.labels.services}</p></div><table><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>{invoice.items?.map((item,index)=><tr key={item.id}><td>{String(index+1).padStart(2,"0")}</td><td><strong>{item.description}</strong>{item.service_period_start&&<small>{item.service_period_start} — {item.service_period_end}</small>}</td><td>{item.quantity}</td><td>{money(item.unit_price,invoice.currency)}</td><td>{money(item.line_total,invoice.currency)}</td></tr>)}</tbody></table></section>,
    totals:<section className="invoice-totals" key="totals"><div><span>Subtotal</span><strong>{money(invoice.subtotal,invoice.currency)}</strong></div>{config.visibility.discount&&invoice.discount>0&&<div><span>Discount</span><strong>− {money(invoice.discount,invoice.currency)}</strong></div>}<div><span>Payments received</span><strong>{money(invoice.amount_paid,invoice.currency)}</strong></div><div className="invoice-total-due"><span>{config.labels.totalDue}</span><strong>{money(invoice.balance_due,invoice.currency)}</strong></div></section>,
    paymentInstructions:(invoice.payment_instructions||methods.length)?<section className="invoice-notes invoice-payment-instructions" key="paymentInstructions"><div className="invoice-section-marker">03</div><div><p className="invoice-label">Payment instructions</p>{invoice.payment_instructions&&<p>{invoice.payment_instructions}</p>}{methods.length>0&&<div className="invoice-methods">{methods.map(method=><span key={String(method)}>{method}</span>)}</div>}</div></section>:null,
    payments:invoice.invoice_payments?.length?<section className="invoice-receipts" key="payments"><p className="invoice-label">Payments received</p>{invoice.invoice_payments.map(payment=><div key={payment.id}><span>{payment.paid_on} · {payment.payment_method.toUpperCase()}{payment.transaction_reference?` · ${payment.transaction_reference}`:""}</span><strong>{money(payment.amount,invoice.currency)}</strong></div>)}</section>:null,
    terms:invoice.terms?<section className="invoice-notes invoice-terms" key="terms"><p className="invoice-label">Terms</p><p>{invoice.terms}</p></section>:null,
    stamp:<footer className="invoice-footer" key="stamp"><div><strong>{str(company.footer)||"Thank you for your business."}</strong><span>Document generated by idevelopit-vault</span></div>{stampUrl?<div className="invoice-stamp"><img src={stampUrl} alt="Company stamp" style={{width:config.stampWidth}}/><span>Issued {invoice.finalized_at?.slice(0,10)||invoice.invoice_date}</span></div>:<div className="invoice-issued"><span>Issued</span><strong>{invoice.finalized_at?.slice(0,10)||invoice.invoice_date}</strong></div>}</footer>,
  };
  const order=[...config.sections,...Object.keys(blocks).filter(key=>!config.sections.includes(key))];
  return <article className={`invoice-document invoice-${config.orientation} invoice-background-${config.backgroundStyle??"clean"}`} style={{"--invoice-color":config.primaryColor,"--invoice-font":config.fontFamily} as CSSProperties}>{config.backgroundStyle==="idevelopit-wave"&&<DocumentWave className="invoice-wave-background"/>}<span className="invoice-document-number">{invoice.invoice_number}</span><div className="invoice-doc-flow">{order.map(key=>blocks[key])}</div></article>;
}
