"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, FilePlus2, LoaderCircle, Pause, Play, Repeat2, UsersRound, X } from "lucide-react";
import { BillingLineEditor, emptyBillingLine } from "@/components/billing/shared/BillingLineEditor";
import { CustomerBillingProfile, customerBillingValue, type CustomerBillingValue } from "@/components/billing/shared/CustomerBillingProfile";
import { createInvoiceFromContract, listContracts, listTemplates, saveContract } from "@/lib/billing";
import { validateContract } from "@/lib/billing-validation";
import { syncCustomerBilling } from "@/lib/customer-billing";
import { listContactsPage, listServices } from "@/lib/db";
import { fmtDay } from "@/lib/format";
import { createClient } from "@/lib/supabase/client";
import type { BillingLineInput, ClientContract, Contact, ContractStatus, DocumentTemplate, Service } from "@/types/db";

const today=new Date().toISOString().slice(0,10);
const initial={contact_id:"",contract_number:"",title:"",start_date:today,end_date:"",billing_day:1,due_days:7,currency:"USD",status:"draft" as ContractStatus,template_id:"",notes:""};
function monthRange(){const d=new Date();return{start:new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10),end:new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10)}}

export function ContractsClient(){
  const [rows,setRows]=useState<ClientContract[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[services,setServices]=useState<Service[]>([]),[templates,setTemplates]=useState<DocumentTemplate[]>([]);
  const [editing,setEditing]=useState<ClientContract|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState(initial),[items,setItems]=useState<BillingLineInput[]>([emptyBillingLine()]),[billing,setBilling]=useState<CustomerBillingValue>(customerBillingValue());
  const [busy,setBusy]=useState(true),[message,setMessage]=useState(""),[editorReady,setEditorReady]=useState(false);
  const load=useCallback(async()=>{setBusy(true);try{setRows(await listContracts(createClient()));}catch(e){setMessage(e instanceof Error?e.message:"Contracts could not load.");}finally{setBusy(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const metrics=useMemo(()=>({active:rows.filter(r=>r.status==="active").length,paused:rows.filter(r=>r.status==="paused").length,customers:new Set(rows.map(r=>r.contact_id)).size}),[rows]);
  async function show(contract?:ClientContract){setBusy(true);setMessage("");try{let availableContacts=contacts;if(!editorReady){const s=createClient();const [contactPage,serviceRows,templateRows]=await Promise.all([listContactsPage(s,{page:1,pageSize:100,filter:"customers"}),listServices(s),listTemplates(s)]);availableContacts=contactPage.rows;setContacts(availableContacts);setServices(serviceRows);setTemplates(templateRows.filter(t=>t.document_type==="invoice"));setEditorReady(true)}const contact=availableContacts.find(c=>c.id===contract?.contact_id);setEditing(contract??null);setForm(contract?{contact_id:contract.contact_id,contract_number:contract.contract_number??"",title:contract.title,start_date:contract.start_date,end_date:contract.end_date??"",billing_day:contract.billing_day,due_days:contract.due_days,currency:contract.currency,status:contract.status,template_id:contract.template_id??"",notes:contract.notes??""}:initial);setBilling(customerBillingValue(contact));setItems(contract?.items?.map(i=>({...i}))??[emptyBillingLine()]);setOpen(true)}catch(e){setMessage(e instanceof Error?e.message:"Contract editor data could not load.")}finally{setBusy(false)}}
  function chooseCustomer(id:string){const contact=contacts.find(c=>c.id===id);setForm(current=>({...current,contact_id:id}));setBilling(customerBillingValue(contact))}
  async function save(e:FormEvent){e.preventDefault();const issue=validateContract({...form,items});if(issue)return setMessage(issue);setBusy(true);try{const s=createClient();await syncCustomerBilling(s,form.contact_id,billing);await saveContract(s,form,items,editing?.id);setOpen(false);await load()}catch(err){setMessage(err instanceof Error?err.message:"Contract could not save.")}finally{setBusy(false)}}
  async function changeStatus(row:ClientContract,status:ContractStatus){try{await saveContract(createClient(),{...row,status},row.items??[],row.id);await load()}catch(e){setMessage(e instanceof Error?e.message:"Status could not update.")}}
  async function generate(row:ClientContract){const range=monthRange();setBusy(true);try{await createInvoiceFromContract(createClient(),row.id,range.start,range.end);setMessage("Invoice draft created. Open Invoices to review it.")}catch(e){setMessage(e instanceof Error?e.message:"Invoice could not be generated.")}finally{setBusy(false)}}

  return <div className="billing-view">
    <section className="stat-grid billing-stat-grid" aria-label="Contract totals"><article className="stat-card"><span className="stat-icon"><Repeat2 size={17}/></span><div><p>Active contracts</p><strong>{metrics.active}</strong><small>ready for monthly billing</small></div></article><article className="stat-card attention-stat"><span className="stat-icon"><Pause size={17}/></span><div><p>Paused</p><strong>{metrics.paused}</strong><small>not generating invoices</small></div></article><article className="stat-card"><span className="stat-icon"><UsersRound size={17}/></span><div><p>Customers</p><strong>{metrics.customers}</strong><small>with recurring agreements</small></div></article></section>
    {message&&<div className="page-error" role="status">{message}<button onClick={()=>setMessage("")}>Dismiss</button></div>}
    <section className="surface billing-list-surface"><header className="surface-toolbar billing-toolbar"><div className="toolbar-heading"><p className="eyebrow">Recurring billing</p><h2>Monthly contracts</h2></div><span className="toolbar-count">{rows.length} agreements</span><button className="button button-primary" onClick={()=>show()}><FilePlus2 size={15}/> New contract</button></header>
      <div className="billing-table-wrap"><table className="billing-table contract-ledger-table"><thead><tr><th>Contract</th><th>Customer</th><th>Schedule</th><th>Status</th><th>Services</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><button className="table-link" onClick={()=>show(row)}>{row.title}</button><small>{row.contract_number||"No reference"}</small></td><td><strong className="ledger-customer">{row.contact?.billing_name||row.contact?.name}</strong></td><td><span className="date-cell"><CalendarClock size={12}/>Day {row.billing_day}</span><small>From {fmtDay(row.start_date)} · {row.currency}</small></td><td><span className={`status-pill status-${row.status}`}>{row.status}</span></td><td><span className="service-count">{row.items?.length??0}</span></td><td><div className="row-actions">{row.status==="active"?<><button className="icon-button" onClick={()=>void generate(row)} title="Generate this month"><FilePlus2 size={14}/></button><button className="icon-button" onClick={()=>void changeStatus(row,"paused")} title="Pause"><Pause size={14}/></button></>:<button className="icon-button" onClick={()=>void changeStatus(row,"active")} title="Activate"><Play size={14}/></button>}</div></td></tr>)}</tbody></table></div>
      <div className="mobile-billing-list" aria-label="Contracts">{rows.map(row=><article className="mobile-billing-card" key={row.id}><span className="mobile-billing-icon"><Repeat2 size={16}/></span><button className="mobile-billing-copy" onClick={()=>show(row)}><strong>{row.title}</strong><small>{row.contact?.billing_name||row.contact?.name} · Day {row.billing_day}</small><span className={`status-pill status-${row.status}`}>{row.status}</span></button><span className="mobile-contract-actions">{row.status==="active"?<button className="icon-button" onClick={()=>void generate(row)} aria-label="Generate invoice"><FilePlus2 size={14}/></button>:<button className="icon-button" onClick={()=>void changeStatus(row,"active")} aria-label="Activate contract"><Play size={14}/></button>}</span></article>)}</div>
      {!rows.length&&!busy&&<div className="panel-empty billing-panel-empty"><span><Repeat2 size={19}/></span><div><strong>No monthly contracts</strong><p>Create an agreement to reuse customer services every month.</p></div></div>}{busy&&<div className="feed-loading"><LoaderCircle className="spin-icon" size={16}/> Loading…</div>}
    </section>
    {open&&<div className="modal-layer"><section className="modal billing-modal" role="dialog" aria-modal="true"><header className="modal-header"><div><p className="eyebrow">{editing?"Edit contract":"New contract"}</p><h2>{editing?.title||"Create agreement"}</h2><p className="modal-subtitle">Customer billing details save back to the contact.</p></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close"><X size={18}/></button></header><form onSubmit={save}><div className="billing-workbench"><section className="drawer-section billing-form-panel"><div className="section-heading"><div><p className="eyebrow">Agreement</p><h3>Schedule and terms</h3></div></div><div className="form-grid"><label className="field span-2"><span>Customer</span><select value={form.contact_id} onChange={e=>chooseCustomer(e.target.value)} required><option value="">Choose customer</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.billing_name||c.name}</option>)}</select></label><label className="field"><span>Contract number</span><input value={form.contract_number} onChange={e=>setForm({...form,contract_number:e.target.value})}/></label><label className="field"><span>Title</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label className="field"><span>Start date</span><input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label className="field"><span>End date</span><input type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label><label className="field"><span>Billing day</span><input type="number" min="1" max="28" value={form.billing_day} onChange={e=>setForm({...form,billing_day:Number(e.target.value)})}/></label><label className="field"><span>Due days</span><input type="number" min="0" value={form.due_days} onChange={e=>setForm({...form,due_days:Number(e.target.value)})}/></label><label className="field"><span>Currency</span><input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ContractStatus})}>{["draft","active","paused","ended"].map(value=><option key={value}>{value}</option>)}</select></label><label className="field span-2"><span>Invoice template</span><select value={form.template_id} onChange={e=>setForm({...form,template_id:e.target.value})}><option value="">Default invoice template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div></section><CustomerBillingProfile contact={contacts.find(c=>c.id===form.contact_id)} value={billing} onChange={setBilling}/></div>
      <section className="drawer-section billing-items-section"><div className="section-heading"><div><p className="eyebrow">Recurring services</p><h3>Contract line items</h3></div><span className="section-total">{items.length} items</span></div><BillingLineEditor items={items} services={services} onChange={setItems}/><label className="field"><span>Notes</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></section><footer className="modal-actions"><button type="button" className="button button-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}>Save contract</button></footer></form></section></div>}
  </div>
}
