"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FilePlus2, LoaderCircle, Pause, Play, X } from "lucide-react";
import { BillingLineEditor, emptyBillingLine } from "@/components/BillingLineEditor";
import { createClient } from "@/lib/supabase/client";
import { listContactsPage, listServices } from "@/lib/db";
import { createInvoiceFromContract, listContracts, listTemplates, saveContract } from "@/lib/billing";
import { validateContract } from "@/lib/billing-validation";
import type { BillingLineInput, ClientContract, Contact, ContractStatus, DocumentTemplate, Service } from "@/types/db";

const today = new Date().toISOString().slice(0,10);
const initial = { contact_id:"",contract_number:"",title:"",start_date:today,end_date:"",billing_day:1,due_days:7,currency:"USD",status:"draft" as ContractStatus,template_id:"",notes:"" };
function monthRange() { const d=new Date(); return { start:new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10), end:new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10) }; }

export function ContractsClient() {
  const [rows,setRows]=useState<ClientContract[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[services,setServices]=useState<Service[]>([]),[templates,setTemplates]=useState<DocumentTemplate[]>([]);
  const [editing,setEditing]=useState<ClientContract|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState(initial),[items,setItems]=useState<BillingLineInput[]>([emptyBillingLine()]);
  const [busy,setBusy]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setBusy(true);try{const supabase=createClient();const [contracts,contactPage,serviceRows,templateRows]=await Promise.all([listContracts(supabase),listContactsPage(supabase,{page:1,pageSize:100,filter:"customers"}),listServices(supabase),listTemplates(supabase)]);setRows(contracts);setContacts(contactPage.rows);setServices(serviceRows);setTemplates(templateRows.filter(t=>t.document_type==="invoice"));}catch(e){setError(e instanceof Error?e.message:"Contracts could not load.");}finally{setBusy(false);}},[]);
  useEffect(()=>{void load()},[load]);
  function show(contract?:ClientContract){setEditing(contract??null);setForm(contract?{contact_id:contract.contact_id,contract_number:contract.contract_number??"",title:contract.title,start_date:contract.start_date,end_date:contract.end_date??"",billing_day:contract.billing_day,due_days:contract.due_days,currency:contract.currency,status:contract.status,template_id:contract.template_id??"",notes:contract.notes??""}:initial);setItems(contract?.items?.map((i)=>({...i}))??[emptyBillingLine()]);setOpen(true);}
  async function save(e:FormEvent){e.preventDefault();const issue=validateContract({...form,items});if(issue)return setError(issue);setBusy(true);try{await saveContract(createClient(),form,items,editing?.id);setOpen(false);await load();}catch(err){setError(err instanceof Error?err.message:"Contract could not save.");}finally{setBusy(false);}}
  async function changeStatus(row:ClientContract,status:ContractStatus){try{await saveContract(createClient(),{...row,status},row.items??[],row.id);await load();}catch(e){setError(e instanceof Error?e.message:"Status could not update.");}}
  async function generate(row:ClientContract){const range=monthRange();setBusy(true);try{await createInvoiceFromContract(createClient(),row.id,range.start,range.end);setError("Invoice draft created. Open Invoices to review it.");}catch(e){setError(e instanceof Error?e.message:"Invoice could not be generated.");}finally{setBusy(false);}}
  return <main className="page-stack"><header className="page-heading"><div><p className="eyebrow">Recurring billing</p><h1>Monthly contracts</h1><p>Configure a customer’s monthly services once, then generate reviewable invoice drafts.</p></div><button className="button button-primary" onClick={()=>show()}><FilePlus2 size={16}/> New contract</button></header>{error&&<div className="drawer-error" role="status">{error}</div>}
    <section className="surface"><div className="responsive-table"><table><thead><tr><th>Contract</th><th>Customer</th><th>Schedule</th><th>Status</th><th>Services</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><button className="table-link" onClick={()=>show(row)}>{row.title}</button><small>{row.contract_number||"No reference"}</small></td><td>{row.contact?.billing_name||row.contact?.name}</td><td>Day {row.billing_day} · {row.currency}</td><td><span className={`status-pill status-${row.status}`}>{row.status}</span></td><td>{row.items?.length??0}</td><td><div className="row-actions">{row.status==="active"?<><button className="icon-button" onClick={()=>void generate(row)} title="Generate this month"><FilePlus2 size={15}/></button><button className="icon-button" onClick={()=>void changeStatus(row,"paused")} title="Pause"><Pause size={15}/></button></>:<button className="icon-button" onClick={()=>void changeStatus(row,"active")} title="Activate"><Play size={15}/></button>}</div></td></tr>)}</tbody></table></div>{!rows.length&&!busy&&<p className="empty-state">No contracts yet.</p>}{busy&&<div className="feed-loading"><LoaderCircle className="spin-icon" size={16}/> Loading…</div>}</section>
    {open&&<div className="modal-layer"><section className="modal billing-modal" role="dialog" aria-modal="true"><header className="modal-header"><div><p className="eyebrow">{editing?"Edit":"New"} recurring agreement</p><h2>{editing?.title||"Create contract"}</h2></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></header><form onSubmit={save}><div className="form-grid"><label className="field span-2"><span>Customer</span><select value={form.contact_id} onChange={e=>setForm({...form,contact_id:e.target.value})} required><option value="">Choose customer</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.billing_name||c.name}</option>)}</select></label><label className="field"><span>Contract number</span><input value={form.contract_number} onChange={e=>setForm({...form,contract_number:e.target.value})}/></label><label className="field"><span>Title</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label className="field"><span>Start date</span><input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label className="field"><span>End date (optional)</span><input type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></label><label className="field"><span>Billing day</span><input type="number" min="1" max="28" value={form.billing_day} onChange={e=>setForm({...form,billing_day:Number(e.target.value)})}/></label><label className="field"><span>Due days</span><input type="number" min="0" value={form.due_days} onChange={e=>setForm({...form,due_days:Number(e.target.value)})}/></label><label className="field"><span>Currency</span><input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as ContractStatus})}>{["draft","active","paused","ended"].map(s=><option key={s}>{s}</option>)}</select></label><label className="field span-2"><span>Invoice template</span><select value={form.template_id} onChange={e=>setForm({...form,template_id:e.target.value})}><option value="">Default invoice template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><BillingLineEditor items={items} services={services} onChange={setItems}/><label className="field"><span>Notes</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><footer className="modal-actions"><button type="button" className="button button-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}>Save contract</button></footer></form></section></div>}
  </main>;
}
