import type { CSSProperties, ReactNode } from "react";
import type { AppSettings, Invoice, TemplateConfig } from "@/types/db";
import { money } from "@/lib/format";

const defaults:TemplateConfig={paperSize:"A4",orientation:"portrait",primaryColor:"#111827",fontFamily:"Arial",logoWidth:180,stampWidth:150,sections:["header","billTo","billingDetails","items","totals","paymentInstructions","terms","stamp"],visibility:{companyPhone:true,companyEmail:true,companyWebsite:true,clientAddress:true,clientEmail:true,clientPhone:true,contractReference:true,purchaseOrderReference:true,discount:true,previousBalance:true},labels:{invoiceTitle:"INVOICE",billTo:"BILL TO",services:"SERVICES PROVIDED",totalDue:"TOTAL DUE"}};
function configOf(invoice:Invoice){const source=(invoice.finalized_at?invoice.template_snapshot:invoice.template?.config) as Partial<TemplateConfig>|undefined;return {...defaults,...source,visibility:{...defaults.visibility,...source?.visibility},labels:{...defaults.labels,...source?.labels}}}

export function InvoiceDocument({invoice,liveSettings,logoUrl,stampUrl}:{invoice:Invoice;liveSettings?:AppSettings|null;logoUrl?:string|null;stampUrl?:string|null}){
  const config=configOf(invoice),saved=invoice.company_snapshot as Record<string,any>,clientSaved=invoice.client_snapshot as Record<string,any>;
  const company=invoice.finalized_at?saved:{name:liveSettings?.company_name,tagline:liveSettings?.company_tagline,phone:liveSettings?.company_phone,email:liveSettings?.company_email,website:liveSettings?.company_website,footer:liveSettings?.default_footer,cashEnabled:liveSettings?.cash_enabled,omtEnabled:liveSettings?.omt_enabled,omtRecipientName:liveSettings?.omt_recipient_name,whishEnabled:liveSettings?.whish_enabled,whishRecipientName:liveSettings?.whish_recipient_name};
  const client=invoice.finalized_at?clientSaved:{billingName:invoice.contact?.billing_name||invoice.contact?.name,contactName:invoice.contact?.billing_contact,address:invoice.contact?.billing_address,email:invoice.contact?.email,phone:invoice.contact?.whatsapp};
  const str=(value:unknown)=>typeof value==="string"?value:"";
  const paymentMethods=[company.cashEnabled&&"Cash",company.omtEnabled&&`OMT${company.omtRecipientName?` · ${str(company.omtRecipientName)}`:""}`,company.whishEnabled&&`Whish${company.whishRecipientName?` · ${str(company.whishRecipientName)}`:""}`].filter(Boolean).join(" · ");
  const blocks:Record<string,ReactNode>={
    header:<header className="invoice-doc-header" key="header"><div>{logoUrl&&<img className="invoice-logo" src={logoUrl} alt={`${str(company.name)||"Company"} logo`} style={{width:config.logoWidth}}/>}<p className="invoice-tagline">{str(company.tagline)}</p><h2>{str(company.name)}</h2><div className="invoice-company-lines">{config.visibility.companyPhone&&company.phone&&<span>{str(company.phone)}</span>}{config.visibility.companyEmail&&company.email&&<span>{str(company.email)}</span>}{config.visibility.companyWebsite&&company.website&&<span>{str(company.website)}</span>}</div></div><div className="invoice-identity"><p>{config.labels.invoiceTitle}</p><strong>{invoice.invoice_number}</strong><span className={`status-pill status-${invoice.status}`}>{invoice.status.replace("_"," ")}</span></div></header>,
    billTo:<section className="invoice-bill-to" key="billTo"><p className="invoice-label">{config.labels.billTo}</p><h3>{str(client.billingName)}</h3>{client.contactName&&<p>{str(client.contactName)}</p>}{config.visibility.clientAddress&&client.address&&<p>{str(client.address)}</p>}{config.visibility.clientEmail&&client.email&&<p>{str(client.email)}</p>}{config.visibility.clientPhone&&client.phone&&<p>{str(client.phone)}</p>}</section>,
    billingDetails:<section className="invoice-meta" key="billingDetails"><div><span>Invoice date</span><strong>{invoice.invoice_date}</strong></div><div><span>Due date</span><strong>{invoice.due_date}</strong></div><div><span>Currency</span><strong>{invoice.currency}</strong></div>{invoice.service_period_start&&<div><span>Service period</span><strong>{invoice.service_period_start} — {invoice.service_period_end}</strong></div>}{config.visibility.contractReference&&invoice.contract_reference&&<div><span>Contract</span><strong>{invoice.contract_reference}</strong></div>}{config.visibility.purchaseOrderReference&&invoice.purchase_order_reference&&<div><span>PO reference</span><strong>{invoice.purchase_order_reference}</strong></div>}</section>,
    items:<section className="invoice-items" key="items"><p className="invoice-label">{config.labels.services}</p><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{invoice.items?.map(item=><tr key={item.id}><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.unit_price,invoice.currency)}</td><td>{money(item.line_total,invoice.currency)}</td></tr>)}</tbody></table></section>,
    totals:<section className="invoice-totals" key="totals"><div><span>Subtotal</span><strong>{money(invoice.subtotal,invoice.currency)}</strong></div>{config.visibility.discount&&invoice.discount>0&&<div><span>Discount</span><strong>−{money(invoice.discount,invoice.currency)}</strong></div>}<div><span>Paid</span><strong>{money(invoice.amount_paid,invoice.currency)}</strong></div><div className="invoice-total-due"><span>{config.labels.totalDue}</span><strong>{money(invoice.balance_due,invoice.currency)}</strong></div></section>,
    paymentInstructions:(invoice.payment_instructions||paymentMethods)?<section className="invoice-notes" key="paymentInstructions"><p className="invoice-label">Payment instructions</p>{invoice.payment_instructions&&<p>{invoice.payment_instructions}</p>}{paymentMethods&&<p>Accepted: {paymentMethods}</p>}</section>:null,
    terms:invoice.terms?<section className="invoice-notes" key="terms"><p className="invoice-label">Terms</p><p>{invoice.terms}</p></section>:null,
    stamp:<footer className="invoice-footer" key="stamp"><div>{str(company.footer)||"Thank you for your business."}</div>{stampUrl&&<div className="invoice-stamp"><img src={stampUrl} alt="Company stamp" style={{width:config.stampWidth}}/><span>Issued {invoice.finalized_at?.slice(0,10)||invoice.invoice_date}</span></div>}</footer>,
  };
  const order=[...config.sections,...Object.keys(blocks).filter(key=>!config.sections.includes(key))];
  return <article className={`invoice-document invoice-${config.orientation}`} style={{"--invoice-color":config.primaryColor,"--invoice-font":config.fontFamily} as CSSProperties}><div className="invoice-doc-flow">{order.map(key=>blocks[key])}</div></article>;
}
