"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, Printer, XCircle } from "lucide-react";
import { DraftInvoiceEditor } from "@/components/DraftInvoiceEditor";
import { InvoiceDocument } from "@/components/InvoiceDocument";
import { cancelInvoice, finalizeInvoice, getAppSettings, getInvoice, recordInvoicePayment, signedAssetUrl } from "@/lib/billing";
import { money } from "@/lib/format";
import { createClient } from "@/lib/supabase/client";
import type { AppSettings, Invoice, InvoicePaymentMethod } from "@/types/db";

export function InvoiceDetailsClient({id}:{id:string}) {
  const [invoice,setInvoice]=useState<Invoice|null>(null),[settings,setSettings]=useState<AppSettings|null>(null);
  const [assets,setAssets]=useState({logo:null as string|null,stamp:null as string|null}),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
  const [payment,setPayment]=useState({amount:"",paidOn:new Date().toISOString().slice(0,10),method:"cash" as InvoicePaymentMethod,reference:"",notes:""});
  const load=useCallback(async()=>{setBusy(true);try{const s=createClient();const [row,company]=await Promise.all([getInvoice(s,id),getAppSettings(s)]);setInvoice(row);setSettings(company);const snapshot=row.company_snapshot as Record<string,string>;const [logo,stamp]=await Promise.all([signedAssetUrl(s,row.finalized_at?snapshot.logoUrl:company.logo_url),signedAssetUrl(s,row.finalized_at?snapshot.stampUrl:company.stamp_url)]);setAssets({logo,stamp});}catch(e){setMessage(e instanceof Error?e.message:"Invoice could not load.");}finally{setBusy(false)}},[id]);
  useEffect(()=>{void load()},[load]);
  async function finalize(){setBusy(true);try{await finalizeInvoice(createClient(),id);setMessage("Invoice finalized. Company, client and template details are frozen.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Invoice could not be finalized.");setBusy(false)}}
  async function cancel(){if(!window.confirm(`Cancel ${invoice?.invoice_number}? This keeps the record and cannot be used for payments.`))return;setBusy(true);try{await cancelInvoice(createClient(),id);setMessage("Invoice cancelled.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Invoice could not be cancelled.");setBusy(false)}}
  async function pay(e:FormEvent){e.preventDefault();if(!invoice)return;const amount=Number(payment.amount);if(!Number.isFinite(amount)||amount<=0)return setMessage("Enter a payment greater than zero.");if(amount>invoice.balance_due)return setMessage("Payment exceeds the remaining balance.");setBusy(true);try{await recordInvoicePayment(createClient(),{invoiceId:id,amount,method:payment.method,paidOn:payment.paidOn,transactionReference:payment.reference,notes:payment.notes});setPayment({...payment,amount:"",reference:"",notes:""});setMessage("Payment recorded.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Payment could not save.");setBusy(false)}}
  if(!invoice)return <div className="surface loading-state">{busy&&<LoaderCircle className="spin-icon"/>}{message||"Loading invoice…"}</div>;
  return <main className="page-stack invoice-detail-page">
    <header className="page-heading no-print"><div><p className="eyebrow">Invoice details</p><h1>{invoice.invoice_number}</h1><p>{invoice.status.replace("_"," ")} · {money(invoice.balance_due,invoice.currency)} due</p></div><div className="heading-actions">{invoice.status==="draft"&&<button className="button button-primary" onClick={()=>void finalize()} disabled={busy}><CheckCircle2 size={16}/> Finalize invoice</button>}{!['paid','cancelled'].includes(invoice.status)&&<button className="button button-danger" onClick={()=>void cancel()} disabled={busy}><XCircle size={16}/> Cancel</button>}<button className="button button-secondary" onClick={()=>window.print()}><Printer size={16}/> Print / Save PDF</button></div></header>
    {message&&<div className="drawer-error no-print" role="status">{message}</div>}
    <InvoiceDocument invoice={invoice} liveSettings={settings} logoUrl={assets.logo} stampUrl={assets.stamp}/>
    {invoice.status==="draft"&&<DraftInvoiceEditor invoice={invoice} onSaved={load}/>} 
    <section className="surface payment-panel no-print"><div><p className="eyebrow">Payment history</p><h2>Receipts</h2>{invoice.invoice_payments?.length?<div className="payment-list">{invoice.invoice_payments.map(p=><div className="payment-row" key={p.id}><div><strong>{p.payment_method.toUpperCase()}</strong><small>{p.paid_on}{p.transaction_reference?` · ${p.transaction_reference}`:""}</small></div><strong>{money(p.amount,invoice.currency)}</strong></div>)}</div>:<p className="empty-inline">No invoice payments recorded.</p>}</div>
      {invoice.status!=="draft"&&invoice.status!=="cancelled"&&invoice.balance_due>0&&<form className="payment-entry" onSubmit={pay}><label className="field"><span>Amount received</span><input type="number" min="0.01" step="0.01" max={invoice.balance_due} value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} required/></label><label className="field"><span>Date</span><input type="date" value={payment.paidOn} onChange={e=>setPayment({...payment,paidOn:e.target.value})}/></label><label className="field"><span>Method</span><select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value as InvoicePaymentMethod})}><option value="cash">Cash</option><option value="omt">OMT</option><option value="whish">Whish</option></select></label><label className="field"><span>Transaction reference (optional)</span><input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><label className="field span-2"><span>Note (optional)</span><input value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})}/></label><div className="payment-preview">Remaining after payment: <strong>{money(Math.max(0,invoice.balance_due-(Number(payment.amount)||0)),invoice.currency)}</strong></div><button className="button button-primary" disabled={busy}>Record payment</button></form>}
    </section>
  </main>
}
