"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarSync, Eye, FilePlus2, LoaderCircle, X } from "lucide-react";
import { BillingLineEditor, emptyBillingLine } from "@/components/BillingLineEditor";
import { createInvoice, generateMonthlyInvoices, listInvoices, listTemplates } from "@/lib/billing";
import { calculateTotals, validateInvoice } from "@/lib/billing-validation";
import { listContactsPage, listServices } from "@/lib/db";
import { money } from "@/lib/format";
import { createClient } from "@/lib/supabase/client";
import type { BillingLineInput, Contact, DocumentTemplate, Invoice, InvoiceStatus, Service } from "@/types/db";

const today=new Date().toISOString().slice(0,10);
function addDays(date:string,days:number){const value=new Date(`${date}T12:00:00`);value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)}
const initial={contact_id:"",contract_id:"",template_id:"",invoice_date:today,due_date:addDays(today,7),service_period_start:"",service_period_end:"",currency:"USD",contract_reference:"",purchase_order_reference:"",discount:0,notes:"",terms:"",payment_instructions:""};

export function InvoicesClient(){
  const [rows,setRows]=useState<Invoice[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[services,setServices]=useState<Service[]>([]),[templates,setTemplates]=useState<DocumentTemplate[]>([]),[status,setStatus]=useState("all");
  const [form,setForm]=useState(initial),[items,setItems]=useState<BillingLineInput[]>([emptyBillingLine()]),[open,setOpen]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
  const load=useCallback(async()=>{setBusy(true);try{const s=createClient();const [invoiceRows,contactPage,serviceRows,templateRows]=await Promise.all([listInvoices(s,status),listContactsPage(s,{page:1,pageSize:100,filter:"customers"}),listServices(s),listTemplates(s)]);setRows(invoiceRows);setContacts(contactPage.rows);setServices(serviceRows);setTemplates(templateRows.filter(t=>t.document_type==="invoice"));}catch(e){setMessage(e instanceof Error?e.message:"Invoices could not load.");}finally{setBusy(false)}},[status]);
  useEffect(()=>{void load()},[load]);
  const totals=useMemo(()=>calculateTotals(items,form.discount),[items,form.discount]);
  async function save(e:FormEvent){e.preventDefault();const issue=validateInvoice({...form,items});if(issue)return setMessage(issue);setBusy(true);try{const id=await createInvoice(createClient(),form,items);setOpen(false);window.location.href=`/invoices/${id}`;}catch(err){setMessage(err instanceof Error?err.message:"Invoice could not be created.");setBusy(false)}}
  async function generate(){setBusy(true);setMessage("");try{const report=await generateMonthlyInvoices(createClient(),today.slice(0,8)+"01");setMessage(`${report.created.length} created · ${report.skipped.length} skipped · ${report.errors.length} errors`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Monthly generation failed.");setBusy(false)}}
  return <main className="page-stack"><header className="page-heading"><div><p className="eyebrow">Billing ledger</p><h1>Invoices</h1><p>Generate from recurring contracts or create a one-off invoice.</p></div><div className="heading-actions"><button className="button button-secondary" onClick={()=>void generate()} disabled={busy}><CalendarSync size={16}/> Generate this month</button><button className="button button-primary" onClick={()=>{setForm(initial);setItems([emptyBillingLine()]);setOpen(true)}}><FilePlus2 size={16}/> New invoice</button></div></header>{message&&<div className="drawer-error" role="status">{message}</div>}
    <div className="filter-tabs" role="tablist">{["all","draft","sent","partially_paid","paid","overdue","cancelled"].map(item=><button key={item} className={status===item?"active":""} onClick={()=>setStatus(item)}>{item.replace("_"," ")}</button>)}</div>
    <section className="surface"><div className="responsive-table"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Issued / due</th><th>Status</th><th>Total</th><th>Balance</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.invoice_number}</strong></td><td>{row.contact?.billing_name||row.contact?.name}</td><td>{row.invoice_date}<small>Due {row.due_date}</small></td><td><span className={`status-pill status-${row.status}`}>{row.status.replace("_"," ")}</span></td><td>{money(row.total_amount,row.currency)}</td><td>{money(row.balance_due,row.currency)}</td><td><Link className="icon-button" href={`/invoices/${row.id}`} aria-label="Open invoice"><Eye size={15}/></Link></td></tr>)}</tbody></table></div>{busy&&<div className="feed-loading"><LoaderCircle className="spin-icon" size={16}/> Loading…</div>}{!busy&&!rows.length&&<p className="empty-state">No invoices match this status.</p>}</section>
    {open&&<div className="modal-layer"><section className="modal billing-modal" role="dialog" aria-modal="true"><header className="modal-header"><div><p className="eyebrow">Manual invoice</p><h2>Create a draft</h2></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={18}/></button></header><form onSubmit={save}><div className="form-grid"><label className="field span-2"><span>Customer</span><select value={form.contact_id} onChange={e=>setForm({...form,contact_id:e.target.value})}><option value="">Choose customer</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.billing_name||c.name}</option>)}</select></label><label className="field"><span>Invoice date</span><input type="date" value={form.invoice_date} onChange={e=>setForm({...form,invoice_date:e.target.value})}/></label><label className="field"><span>Due date</span><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label className="field"><span>Period start</span><input type="date" value={form.service_period_start} onChange={e=>setForm({...form,service_period_start:e.target.value})}/></label><label className="field"><span>Period end</span><input type="date" value={form.service_period_end} onChange={e=>setForm({...form,service_period_end:e.target.value})}/></label><label className="field"><span>Currency</span><input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="field"><span>Discount</span><input type="number" min="0" step="0.01" value={form.discount} onChange={e=>setForm({...form,discount:Number(e.target.value)})}/></label><label className="field"><span>Contract reference</span><input value={form.contract_reference} onChange={e=>setForm({...form,contract_reference:e.target.value})}/></label><label className="field"><span>PO reference</span><input value={form.purchase_order_reference} onChange={e=>setForm({...form,purchase_order_reference:e.target.value})}/></label><label className="field span-2"><span>Template</span><select value={form.template_id} onChange={e=>setForm({...form,template_id:e.target.value})}><option value="">Default invoice template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><BillingLineEditor items={items} services={services} onChange={setItems}/><div className="invoice-form-total"><span>Subtotal {money(totals.subtotal,form.currency)}</span><strong>Total {money(totals.total,form.currency)}</strong></div><footer className="modal-actions"><button type="button" className="button button-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}>Create draft</button></footer></form></section></div>}
  </main>
}
