"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { CalendarSync, CircleDollarSign, Eye, FilePlus2, LoaderCircle, ReceiptText, WalletCards, X } from "lucide-react";
import { BillingLineEditor, emptyBillingLine } from "@/components/BillingLineEditor";
import { CustomerBillingProfile, customerBillingValue, type CustomerBillingValue } from "@/components/CustomerBillingProfile";
import { createInvoice, generateMonthlyInvoices, listInvoices, listTemplates } from "@/lib/billing";
import { calculateTotals, validateInvoice } from "@/lib/billing-validation";
import { syncCustomerBilling } from "@/lib/customer-billing";
import { listContactsPage, listServices } from "@/lib/db";
import { money } from "@/lib/format";
import { createClient } from "@/lib/supabase/client";
import type { BillingLineInput, Contact, DocumentTemplate, Invoice, Service } from "@/types/db";

const today=new Date().toISOString().slice(0,10);
function addDays(date:string,days:number){const value=new Date(`${date}T12:00:00`);value.setDate(value.getDate()+days);return value.toISOString().slice(0,10)}
const initial={contact_id:"",contract_id:"",template_id:"",invoice_date:today,due_date:addDays(today,7),service_period_start:"",service_period_end:"",currency:"USD",contract_reference:"",purchase_order_reference:"",discount:0,notes:"",terms:"",payment_instructions:""};

export function InvoicesClient(){
  const [rows,setRows]=useState<Invoice[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[services,setServices]=useState<Service[]>([]),[templates,setTemplates]=useState<DocumentTemplate[]>([]),[status,setStatus]=useState("all");
  const [form,setForm]=useState(initial),[items,setItems]=useState<BillingLineInput[]>([emptyBillingLine()]),[billing,setBilling]=useState<CustomerBillingValue>(customerBillingValue()),[open,setOpen]=useState(false),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
  const load=useCallback(async()=>{setBusy(true);try{const s=createClient();const [invoiceRows,contactPage,serviceRows,templateRows]=await Promise.all([listInvoices(s,status),listContactsPage(s,{page:1,pageSize:100,filter:"customers"}),listServices(s),listTemplates(s)]);setRows(invoiceRows);setContacts(contactPage.rows);setServices(serviceRows);setTemplates(templateRows.filter(t=>t.document_type==="invoice"));}catch(e){setMessage(e instanceof Error?e.message:"Invoices could not load.");}finally{setBusy(false)}},[status]);
  useEffect(()=>{void load()},[load]);
  const totals=useMemo(()=>calculateTotals(items,form.discount),[items,form.discount]);
  const selectedCustomer=contacts.find(c=>c.id===form.contact_id)??null;
  const metrics=useMemo(()=>({billed:rows.reduce((sum,row)=>sum+row.total_amount,0),outstanding:rows.reduce((sum,row)=>sum+row.balance_due,0),paid:rows.filter(row=>row.status==="paid").length}),[rows]);
  function chooseCustomer(id:string){const contact=contacts.find(c=>c.id===id);setForm(current=>({...current,contact_id:id}));setBilling(customerBillingValue(contact));}
  function startInvoice(){setForm(initial);setItems([emptyBillingLine()]);setBilling(customerBillingValue());setOpen(true)}
  async function save(e:FormEvent){e.preventDefault();const issue=validateInvoice({...form,items});if(issue)return setMessage(issue);setBusy(true);try{const s=createClient();await syncCustomerBilling(s,form.contact_id,billing);const id=await createInvoice(s,form,items);setOpen(false);window.location.href=`/invoices/${id}`;}catch(err){setMessage(err instanceof Error?err.message:"Invoice could not be created.");setBusy(false)}}
  async function generate(){setBusy(true);setMessage("");try{const report=await generateMonthlyInvoices(createClient(),today.slice(0,8)+"01");setMessage(`${report.created.length} created · ${report.skipped.length} skipped · ${report.errors.length} errors`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Monthly generation failed.");setBusy(false)}}
  return <main className="page-stack billing-page">
    <header className="billing-hero"><div className="billing-hero-copy"><span className="billing-index">BL / 02</span><p className="eyebrow">Invoice control desk</p><h1>Money promised.<br/><em>Money received.</em></h1><p>Create precise drafts, lock their history, and see what is still due without rebuilding customer details.</p></div><div className="billing-hero-actions"><button className="button button-ghost-light" onClick={()=>void generate()} disabled={busy}><CalendarSync size={16}/> Generate this month</button><button className="button button-accent" onClick={startInvoice}><FilePlus2 size={16}/> New invoice</button></div></header>
    <section className="billing-metrics" aria-label="Invoice summary"><article><ReceiptText size={18}/><span>Total billed</span><strong>{money(metrics.billed)}</strong></article><article><WalletCards size={18}/><span>Still to collect</span><strong>{money(metrics.outstanding)}</strong></article><article><CircleDollarSign size={18}/><span>Paid invoices</span><strong>{metrics.paid}</strong></article></section>
    {message&&<div className="drawer-error" role="status">{message}</div>}
    <div className="billing-ledger-head"><div className="filter-tabs" role="tablist">{["all","draft","sent","partially_paid","paid","overdue","cancelled"].map(item=><button key={item} className={status===item?"active":""} onClick={()=>setStatus(item)}>{item.replace("_"," ")}</button>)}</div><span>{rows.length} records</span></div>
    <section className="surface ledger-surface"><div className="responsive-table"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Issued / due</th><th>Status</th><th>Total</th><th>Balance</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.invoice_number}</strong></td><td>{row.contact?.billing_name||row.contact?.name}</td><td>{row.invoice_date}<small>Due {row.due_date}</small></td><td><span className={`status-pill status-${row.status}`}>{row.status.replace("_"," ")}</span></td><td>{money(row.total_amount,row.currency)}</td><td className="ledger-balance">{money(row.balance_due,row.currency)}</td><td><Link className="icon-button" href={`/invoices/${row.id}`} aria-label="Open invoice"><Eye size={15}/></Link></td></tr>)}</tbody></table></div>{busy&&<div className="feed-loading"><LoaderCircle className="spin-icon" size={16}/> Loading…</div>}{!busy&&!rows.length&&<div className="billing-empty"><ReceiptText size={24}/><strong>No invoices here</strong><p>Create a draft or generate this month’s contract invoices.</p></div>}</section>
    {open&&<div className="modal-layer"><section className="modal billing-modal billing-document-modal" role="dialog" aria-modal="true"><header className="modal-header"><div><p className="eyebrow">New billing document</p><h2>Create invoice draft</h2><p className="modal-subtitle">Customer data stays reusable. Invoice values stay editable.</p></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close"><X size={18}/></button></header><form onSubmit={save}><div className="billing-workbench"><div className="billing-form-panel"><section className="form-chapter"><span className="chapter-number">01</span><div><h3>Customer & dates</h3><p>Start with who is being billed and when payment is due.</p></div></section><div className="form-grid"><label className="field span-2"><span>Customer</span><select value={form.contact_id} onChange={e=>chooseCustomer(e.target.value)} required><option value="">Choose customer</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.billing_name||c.name}</option>)}</select></label><label className="field"><span>Invoice date</span><input type="date" value={form.invoice_date} onChange={e=>setForm({...form,invoice_date:e.target.value})}/></label><label className="field"><span>Due date</span><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label className="field"><span>Period start</span><input type="date" value={form.service_period_start} onChange={e=>setForm({...form,service_period_start:e.target.value})}/></label><label className="field"><span>Period end</span><input type="date" value={form.service_period_end} onChange={e=>setForm({...form,service_period_end:e.target.value})}/></label><label className="field"><span>Currency</span><input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="field"><span>Discount</span><input type="number" min="0" step="0.01" value={form.discount} onChange={e=>setForm({...form,discount:Number(e.target.value)})}/></label><label className="field"><span>Contract reference</span><input value={form.contract_reference} onChange={e=>setForm({...form,contract_reference:e.target.value})}/></label><label className="field"><span>PO reference</span><input value={form.purchase_order_reference} onChange={e=>setForm({...form,purchase_order_reference:e.target.value})}/></label><label className="field span-2"><span>Template</span><select value={form.template_id} onChange={e=>setForm({...form,template_id:e.target.value})}><option value="">Default invoice template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div></div><CustomerBillingProfile contact={selectedCustomer} value={billing} onChange={setBilling}/></div>
      <section className="line-items-chapter"><div className="form-chapter"><span className="chapter-number">02</span><div><h3>Services & pricing</h3><p>Select reusable services or write a custom line.</p></div></div><BillingLineEditor items={items} services={services} onChange={setItems}/><div className="invoice-form-total"><span>Subtotal {money(totals.subtotal,form.currency)}</span><strong>Total {money(totals.total,form.currency)}</strong></div></section><footer className="modal-actions sticky-actions"><span>Invoice number is assigned only when this draft is created.</span><div><button type="button" className="button button-secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}>Create draft</button></div></footer></form></section></div>}
  </main>
}
